services:
  django:
    container_name: management_event
    build: .
    # command: sleep infinity
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - . :/code
    ports:
      - "8001:8000"
  postgres:
    container_name: management_event_db
    image: postgres:15.10
    environment:
      POSTGRES_DB: evman
      POSTGRES_USER: evman
      POSTGRES_PASSWORD: evman
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5532:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata